# Generated by Django 4.2.5 on 2023-09-29 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_remove_user_address_remove_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
