# Generated by Django 4.2.5 on 2023-09-27 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_category_gender_alter_product_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='page_views',
            field=models.IntegerField(default=0),
        ),
    ]
