# Generated by Django 4.2.5 on 2023-09-28 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_remove_user_address_remove_user_phone'),
        ('order', '0002_remove_orderitem_date_added_order_delivery_info_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='shipping_address',
            field=models.ForeignKey(default='Address is deleated', on_delete=django.db.models.deletion.SET_DEFAULT, to='account.shippingaddress'),
        ),
    ]
