# Generated by Django 4.2.5 on 2023-09-29 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_shippingaddress_is_active'),
        ('order', '0003_alter_order_shipping_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='shipping_address',
            field=models.ForeignKey(default=13, on_delete=django.db.models.deletion.SET_DEFAULT, to='account.shippingaddress'),
        ),
    ]
